import type { PlanetDefinition, PlanetId, TravelSpot } from "@/types/world";

export const HOME_PLANET_ID: PlanetId = "home";

export const planets: PlanetDefinition[] = [
  {
    id: "home",
    name: "작은 초록별",
    subtitle: "처음 산책이 시작되는 부드러운 행성",
    groundColor: "#b9ddbe",
    accentColor: "#f7c76b",
    fogColor: "#d4e7ea",
    startPoint: { theta: 0.1, phi: 0.32, heading: 0.2 },
  },
  {
    id: "dawn",
    name: "새벽 편지별",
    subtitle: "연한 빛과 종이배가 머무는 행성",
    groundColor: "#d7d5b3",
    accentColor: "#f5b66c",
    fogColor: "#eadfc9",
    startPoint: { theta: 3.8, phi: 1.3, heading: -0.7 },
  },
  {
    id: "ember",
    name: "붉은 먼지별",
    subtitle: "낮은 화산과 수정 조각이 반짝이는 행성",
    groundColor: "#c99a7a",
    accentColor: "#ffd07a",
    fogColor: "#e6c8b4",
    startPoint: { theta: 5.3, phi: 1.55, heading: 0.5 },
  },
  {
    id: "violet",
    name: "보랏빛 궤도별",
    subtitle: "작은 위성과 망원경이 밤을 지키는 행성",
    groundColor: "#b9afd7",
    accentColor: "#c8ecff",
    fogColor: "#d6d7ee",
    startPoint: { theta: 1.2, phi: 1.4, heading: 1.1 },
  },
];

export const planetsById: Record<PlanetId, PlanetDefinition> = {
  home: planets[0],
  dawn: planets[1],
  ember: planets[2],
  violet: planets[3],
};

export const getPlanet = (id: PlanetId): PlanetDefinition => planetsById[id] ?? planetsById[HOME_PLANET_ID];

export const travelSpots: TravelSpot[] = [
  // 작은 초록별: 시작 행성도 여러 갈래로 열린다.
  {
    id: "home-dawn-lantern",
    planetId: "home",
    targetPlanetId: "dawn",
    theta: 0.75,
    phi: 1.75,
    heading: -0.4,
    targetPoint: { theta: 3.8, phi: 1.3, heading: -0.7 },
    label: "새벽 편지별로",
    description: "종이배가 떠 있는 별로 건너가기",
    color: "#ffe2a8",
  },
  {
    id: "home-ember-volcano",
    planetId: "home",
    targetPlanetId: "ember",
    theta: 2.2,
    phi: 1.15,
    heading: 0.6,
    targetPoint: { theta: 5.3, phi: 1.55, heading: 0.5 },
    label: "붉은 먼지별로",
    description: "따뜻한 화산빛이 보이는 별로 이동",
    color: "#ffb287",
    variant: 1,
  },
  {
    id: "home-violet-telescope",
    planetId: "home",
    targetPlanetId: "violet",
    theta: 3.95,
    phi: 1.5,
    heading: -0.2,
    targetPoint: { theta: 1.2, phi: 1.4, heading: 1.1 },
    label: "보랏빛 궤도별로",
    description: "망원경 불빛이 깜박이는 별로 이동",
    color: "#d9d2ff",
    variant: 2,
  },
  {
    id: "home-dawn-pond",
    planetId: "home",
    targetPlanetId: "dawn",
    theta: 4.85,
    phi: 2.08,
    heading: 1.2,
    targetPoint: { theta: 0.55, phi: 1.92, heading: 0.35 },
    label: "새벽 편지별 남쪽으로",
    description: "반대편 연못가로 부드럽게 이동",
    color: "#bdeaf2",
  },
  {
    id: "home-ember-crystal",
    planetId: "home",
    targetPlanetId: "ember",
    theta: 5.75,
    phi: 1.08,
    heading: -1.0,
    targetPoint: { theta: 2.35, phi: 1.1, heading: -0.45 },
    label: "수정 들판으로",
    description: "붉은 먼지별의 반짝이는 들판으로 이동",
    color: "#ffd98a",
    variant: 1,
  },

  // 새벽 편지별
  {
    id: "dawn-home-rose",
    planetId: "dawn",
    targetPlanetId: "home",
    theta: 0.55,
    phi: 1.92,
    heading: 0.35,
    targetPoint: { theta: 1.0, phi: 1.0, heading: 0.6 },
    label: "작은 초록별로",
    description: "장미와 여우가 있는 첫 행성으로 돌아가기",
    color: "#d7efbe",
  },
  {
    id: "dawn-violet-station",
    planetId: "dawn",
    targetPlanetId: "violet",
    theta: 1.68,
    phi: 1.05,
    heading: -0.85,
    targetPoint: { theta: 4.6, phi: 1.2, heading: -0.3 },
    label: "궤도 정거장으로",
    description: "보랏빛 궤도별의 작은 위성 곁으로 이동",
    color: "#c8ecff",
    variant: 2,
  },
  {
    id: "dawn-ember-gate",
    planetId: "dawn",
    targetPlanetId: "ember",
    theta: 2.7,
    phi: 1.72,
    heading: 0.9,
    targetPoint: { theta: 0.6, phi: 1.95, heading: 0.8 },
    label: "붉은 바람길로",
    description: "낮은 먼지가 흐르는 행성으로 이동",
    color: "#ffb287",
    variant: 1,
  },
  {
    id: "dawn-home-lamp",
    planetId: "dawn",
    targetPlanetId: "home",
    theta: 4.05,
    phi: 1.28,
    heading: 0.1,
    targetPoint: { theta: 4.9, phi: 1.75, heading: 1.1 },
    label: "초록별 가로등길로",
    description: "작은 초록별의 밤길 근처로 이동",
    color: "#fff0bd",
  },
  {
    id: "dawn-violet-north",
    planetId: "dawn",
    targetPlanetId: "violet",
    theta: 5.35,
    phi: 2.18,
    heading: -1.2,
    targetPoint: { theta: 2.65, phi: 1.85, heading: 0.6 },
    label: "보랏빛 북쪽 언덕으로",
    description: "작은 망원경들이 모인 언덕으로 이동",
    color: "#e6d8ff",
    variant: 2,
  },

  // 붉은 먼지별
  {
    id: "ember-home-baobab",
    planetId: "ember",
    targetPlanetId: "home",
    theta: 0.6,
    phi: 1.95,
    heading: 0.8,
    targetPoint: { theta: 3.0, phi: 1.85, heading: -0.2 },
    label: "바오바브 언덕으로",
    description: "초록별의 키 큰 나무 근처로 이동",
    color: "#cfeabf",
  },
  {
    id: "ember-dawn-letters",
    planetId: "ember",
    targetPlanetId: "dawn",
    theta: 1.58,
    phi: 1.38,
    heading: -0.25,
    targetPoint: { theta: 2.95, phi: 1.25, heading: 1.0 },
    label: "편지 바람길로",
    description: "새벽 편지별의 바람개비 곁으로 이동",
    color: "#ffe2a8",
  },
  {
    id: "ember-violet-ring",
    planetId: "ember",
    targetPlanetId: "violet",
    theta: 2.35,
    phi: 1.1,
    heading: -0.45,
    targetPoint: { theta: 5.45, phi: 1.65, heading: -0.8 },
    label: "고리 돌무덤으로",
    description: "보랏빛 궤도별의 돌고리로 이동",
    color: "#d9d2ff",
    variant: 2,
  },
  {
    id: "ember-dawn-pond",
    planetId: "ember",
    targetPlanetId: "dawn",
    theta: 3.92,
    phi: 2.02,
    heading: 1.2,
    targetPoint: { theta: 4.95, phi: 1.75, heading: -0.9 },
    label: "새벽 연못가로",
    description: "종이배가 있는 조용한 연못으로 이동",
    color: "#bdeaf2",
  },
  {
    id: "ember-home-fox",
    planetId: "ember",
    targetPlanetId: "home",
    theta: 5.3,
    phi: 1.55,
    heading: 0.5,
    targetPoint: { theta: 1.45, phi: 0.95, heading: 0.4 },
    label: "여우가 기다리는 곳으로",
    description: "초록별의 작은 친구 곁으로 이동",
    color: "#f6c08a",
  },

  // 보랏빛 궤도별
  {
    id: "violet-dawn-harbor",
    planetId: "violet",
    targetPlanetId: "dawn",
    theta: 0.65,
    phi: 1.3,
    heading: 0.9,
    targetPoint: { theta: 0.55, phi: 1.92, heading: 0.35 },
    label: "새벽 항구로",
    description: "종이배와 조용한 물가로 이동",
    color: "#bdeaf2",
  },
  {
    id: "violet-ember-crater",
    planetId: "violet",
    targetPlanetId: "ember",
    theta: 1.85,
    phi: 2.02,
    heading: -0.4,
    targetPoint: { theta: 3.92, phi: 2.02, heading: 1.2 },
    label: "낮은 분화구로",
    description: "붉은 먼지별의 따뜻한 분화구로 이동",
    color: "#ffb287",
    variant: 1,
  },
  {
    id: "violet-home-window",
    planetId: "violet",
    targetPlanetId: "home",
    theta: 2.65,
    phi: 1.85,
    heading: 0.6,
    targetPoint: { theta: 5.65, phi: 1.2, heading: -0.7 },
    label: "초록별 창가로",
    description: "작은 불빛이 보이는 첫 행성으로 이동",
    color: "#fff0bd",
  },
  {
    id: "violet-ember-south",
    planetId: "violet",
    targetPlanetId: "ember",
    theta: 4.6,
    phi: 1.2,
    heading: -0.3,
    targetPoint: { theta: 1.58, phi: 1.38, heading: -0.25 },
    label: "붉은 수정 능선으로",
    description: "수정 조각이 이어진 능선으로 이동",
    color: "#ffd98a",
    variant: 1,
  },
  {
    id: "violet-dawn-wind",
    planetId: "violet",
    targetPlanetId: "dawn",
    theta: 5.45,
    phi: 1.65,
    heading: -0.8,
    targetPoint: { theta: 2.95, phi: 1.25, heading: 1.0 },
    label: "바람개비 언덕으로",
    description: "새벽 편지별의 바람 많은 언덕으로 이동",
    color: "#ffe2a8",
  },
];

export const getTravelSpotsForPlanet = (planetId: PlanetId): TravelSpot[] =>
  travelSpots.filter((spot) => spot.planetId === planetId);

export const getTravelSpot = (id: string | null): TravelSpot | null =>
  id ? travelSpots.find((spot) => spot.id === id) ?? null : null;
